### ISSUE TITLE
Thumnail on 'inset image' as well as 'attach'

### ISSUE THREAD

**Issue by chyandour5** [canonknipser/imthumbnailer#9]
Hi,
Would it be possible to have the thumbnailet work when inserting a remote image into a post, example:

`[img]https://cursorium.co.uk/gallery/_data/i/upload/2018/06/11/20180611113938-c9a106df-me.jpg[/img]
`

As well as it working with attachments?
Regards
Chris

**Comment by canonknipser** [comment]
No, that is not possible with the current extension. The code for attachments and the code for external images are complete different.

You can do it out of the box by combining two bbCodes, if you put the thumbnail image on the remote site also:
`[url=link-to-full-image][img]link-to-thumbnail-image[/img][/url]`
A lot image hosting sites create images in different sizes when you upload them, so this could be a way to go.


Thank you for your request, but as i don't plan to implement, I'll set it to "won't fix" and close it in the next days.

**Comment by canonknipser** [comment]
Closing
